# Generated by Django 4.2 on 2024-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('P.A.M', 'P.A.M'), ('Entorno', 'Entorno')], max_length=100, null=True),
        ),
    ]
