# Generated by Django 4.2 on 2024-03-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('P.A.M', 'P.A.M'), ('Entorno', 'Entorno')], default='P.A.M', max_length=100, null=True),
        ),
    ]
