# Generated by Django 4.2 on 2024-03-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_additionalcellphone_profile_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAMEntornoRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_date', models.DateTimeField(auto_now_add=True)),
                ('entorno_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entorno_users', to='profiles.profile')),
                ('pam_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_user', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Relación P.A.M-Entorno',
                'verbose_name_plural': 'Relaciones P.A.M-Entorno',
                'unique_together': {('pam_user', 'entorno_user')},
            },
        ),
    ]
