# Generated by Django 4.2 on 2024-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_pamentornorelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pams',
            field=models.ManyToManyField(blank=True, related_name='entornos', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='PAMEntornoRelationship',
        ),
    ]
