# Generated by Django 4.2 on 2024-03-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_pams_delete_pamentornorelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pams',
            new_name='affiliations',
        ),
    ]
