# Generated by Django 4.2 on 2024-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_pams_profile_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_token',
            field=models.CharField(blank=True, error_messages={'unique': 'Este token de dispositivo ya está registrado.'}, max_length=255, null=True, unique=True),
        ),
    ]
