# Generated by Django 4.2 on 2024-03-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('taxi', 'Taxi'), ('payment', 'Pago')], max_length=100, null=True, verbose_name='Tipo de Servicio')),
                ('date_of_attention', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Atención')),
                ('details', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detalles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solitud de Atención',
                'verbose_name_plural': 'Solitudes de Atención',
            },
        ),
    ]
