# Generated by Django 4.2 on 2024-03-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_help_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=100),
        ),
    ]
