# Generated by Django 4.2 on 2024-04-01 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_help_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestattention',
            options={'verbose_name': 'Solicitud de Atención', 'verbose_name_plural': 'Solicitudes de Atención'},
        ),
        migrations.AddField(
            model_name='requestattention',
            name='PAMid',
            field=models.CharField(default='', max_length=100, verbose_name='PAMid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestattention',
            name='atendido_por',
            field=models.CharField(default='', max_length=100, verbose_name='Atendido Por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestattention',
            name='estado',
            field=models.CharField(default='', max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestattention',
            name='telefono_de_contacto',
            field=models.CharField(default='', max_length=100, verbose_name='Teléfono de Contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestattention',
            name='time_of_attention',
            field=models.TimeField(default=datetime.time(1, 13, 30, 965493), verbose_name='Hora de Atención'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestattention',
            name='date_of_attention',
            field=models.DateField(verbose_name='Fecha de Atención'),
        ),
    ]
