# Generated by Django 4.2 on 2024-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_alter_requestattention_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestattention',
            name='date_of_attention',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Atención'),
        ),
        migrations.AlterField(
            model_name='requestattention',
            name='time_of_attention',
            field=models.TimeField(auto_now=True, verbose_name='Hora de Atención'),
        ),
    ]
