# Generated by Django 4.2 on 2024-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0007_alter_requestattention_date_of_attention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestattention',
            name='date_of_attention',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='requestattention',
            name='time_of_attention',
            field=models.TimeField(auto_now=True, verbose_name='Hora'),
        ),
    ]
