# Generated by Django 4.2 on 2024-04-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0008_alter_requestattention_date_of_attention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestattention',
            name='PAMid',
            field=models.CharField(max_length=100, verbose_name='PAM id'),
        ),
        migrations.AlterField(
            model_name='requestattention',
            name='type',
            field=models.CharField(blank=True, choices=[('taxi', 'Taxi'), ('payment', 'Pago')], max_length=100, null=True, verbose_name='Pantalla'),
        ),
        migrations.AlterField(
            model_name='requestattention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombres y Apellidos'),
        ),
    ]
