# Generated by Django 4.2 on 2024-04-01 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help', '0009_alter_requestattention_pamid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='help',
            name='scream',
            field=models.CharField(max_length=100, verbose_name='Pantalla'),
        ),
        migrations.AlterField(
            model_name='help',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='help',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
