# Generated by Django 4.2 on 2024-04-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0010_alter_help_details_alter_help_scream_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='scream',
            new_name='screen',
        ),
    ]
